use strum_macros;

#[derive(Debug, PartialEq, strum_macros::FromRepr, strum_macros::Display)]
#[repr(u32)]
pub enum Type {
    #[strum(to_string = "SECBOOT AuthWrongMagicNumber")]
    AuthWrongMagicNumber = 0x2C000101,
    #[strum(to_string = "SECBOOT AuthImageLength")]
    AuthImageLength = 0x2C000102,
    #[strum(to_string = "SECBOOT AuthenticationExtensionHeaderMissing")]
    AuthenticationExtensionHeaderMissing = 0x2C000103,
    #[strum(to_string = "SECBOOT AuthEccAlgoP256NIST")]
    AuthEccAlgoP256NIST = 0x2C000104,
    #[strum(to_string = "SECBOOT AuthEccAlgoBrainPool256")]
    AuthEccAlgoBrainPool256 = 0x2C000105,
    #[strum(to_string = "SECBOOT AuthEccAlgoP384NIST")]
    AuthEccAlgoP384NIST = 0x2C000106,
    #[strum(to_string = "SECBOOT AuthEccAlgoBrainPool384")]
    AuthEccAlgoBrainPool384 = 0x2C000107,
    #[strum(to_string = "SECBOOT AuthEccAlgoUnknown")]
    AuthEccAlgoUnknown = 0x2C000108,
    #[strum(to_string = "SECBOOT AuthImageNotEncrypted")]
    AuthImageNotEncrypted = 0x2C00010A,
    #[strum(to_string = "SECBOOT AuthImageEncrypted")]
    AuthImageEncrypted = 0x2C00010B,
    #[strum(to_string = "SECBOOT AuthImageDecryptionFailed")]
    AuthImageDecryptionFailed = 0x2C00010D,
    #[strum(to_string = "SECBOOT AuthImageDecryptionSucceed")]
    AuthImageDecryptionSucceed = 0x2C00010E,
    #[strum(to_string = "SECBOOT AuthPubKeyVerifFailed")]
    AuthPubKeyVerifFailed = 0x2C00010F,
    #[strum(to_string = "SECBOOT AuthImageSignatureKo")]
    AuthImageSignatureKo = 0x2C000112,
    #[strum(to_string = "SECBOOT AuthImageSignatureOk")]
    AuthImageSignatureOk = 0x2C000113,
    #[strum(to_string = "SECBOOT AuthPubKeyVerifOk")]
    AuthPubKeyVerifOk = 0x2C000114,
    #[strum(to_string = "SECBOOT AuthWrongImageChecksum")]
    AuthWrongImageChecksum = 0x2C000201,
    #[strum(to_string = "SECBOOT AuthPublicKeyIsRevoked")]
    AuthPublicKeyIsRevoked = 0x2C000202,
    #[strum(to_string = "SECBOOT AuthPublicKeyNotRevoked")]
    AuthPublicKeyNotRevoked = 0x2C000203,
    #[strum(to_string = "SECBOOT AuthWrongImageVersion")]
    AuthWrongImageVersion = 0x2C000204,
    #[strum(to_string = "SECBOOT AuthPubKHashTableNotEqualToRef")]
    AuthPubKHashTableNotEqualToRef = 0x2C000207,
    #[strum(to_string = "SECBOOT AuthImageEntryPoint")]
    AuthImageEntryPoint = 0x2C000208,
    #[strum(to_string = "SECBOOT AuthPublicKeyHashVerificationError")]
    AuthPublicKeyHashVerificationError = 0x2C00020B,
    #[strum(to_string = "SECBOOT DecryptUsingCrypDriver")]
    DecryptUsingCrypDriver = 0x2C000302,
    #[strum(to_string = "SECBOOT DecryptUsingSaesDriver")]
    DecryptUsingSaesDriver = 0x2C000303,
    #[strum(to_string = "SECBOOT DecryptHashIntegrityError")]
    DecryptHashIntegrityError = 0x2C00030A,
    #[strum(to_string = "SECBOOT AuthDecisionIsJumpToImage")]
    AuthDecisionIsJumpToImage = 0x2C004008,
    #[strum(to_string = "BOOTCORE LogicalResetSystem")]
    LogicalResetSystem = 0x00000010,
    #[strum(to_string = "BOOTCORE LogicalResetStKeyProvisioning")]
    LogicalResetStKeyProvisioning = 0x00000011,
    #[strum(to_string = "BOOTCORE LogicalResetInvalid")]
    LogicalResetInvalid = 0x00000012,
    #[strum(to_string = "BOOTCORE ChipModeInvalid")]
    ChipModeInvalid = 0x00000020,
    #[strum(to_string = "BOOTCORE ChipModeStVirgin")]
    ChipModeStVirgin = 0x00000021,
    #[strum(to_string = "BOOTCORE ChipModeStOpen")]
    ChipModeStOpen = 0x00000022,
    #[strum(to_string = "BOOTCORE ChipModeOpen")]
    ChipModeOpen = 0x00000023,
    #[strum(to_string = "BOOTCORE ChipModeStClosedVirgin")]
    ChipModeStClosedVirgin = 0x00000024,
    #[strum(to_string = "BOOTCORE ChipModeClosedUnlocked")]
    ChipModeClosedUnlocked = 0x00000025,
    #[strum(to_string = "BOOTCORE DevBoot")]
    DevBoot = 0x00000026,
    #[strum(to_string = "BOOTCORE ChipModeClosedLockedUnprovd")]
    ChipModeClosedLockedUnprovd = 0x00000027,
    #[strum(to_string = "BOOTCORE ChipModeClosedLockedProvd")]
    ChipModeClosedLockedProvd = 0x00000028,
    #[strum(to_string = "BOOTCORE BootActionInvalid")]
    BootActionInvalid = 0x00000030,
    #[strum(to_string = "BOOTCORE BootActionNoBoot")]
    BootActionNoBoot = 0x00000031,
    #[strum(to_string = "BOOTCORE BootActionStKeyProv")]
    BootActionStKeyProv = 0x00000032,
    #[strum(to_string = "BOOTCORE BootActionSecureBootProcess")]
    BootActionSecureBootProcess = 0x00000033,
    #[strum(to_string = "BOOTCORE BootActionDevBoot")]
    BootActionDevBoot = 0x00000034,
    #[strum(to_string = "BOOTCORE BootCfgOtpWordValue")]
    BootCfgOtpWordValue = 0x00000052,
    #[strum(to_string = "BOOTCORE BootCfgAfmuxOtpWord1Value")]
    BootCfgAfmuxOtpWord1Value = 0x00000053,
    #[strum(to_string = "BOOTCORE BootCfgAfmuxOtpWord2Value")]
    BootCfgAfmuxOtpWord2Value = 0x00000054,
    #[strum(to_string = "BOOTCORE BootCfgAfmuxOtpWord3Value")]
    BootCfgAfmuxOtpWord3Value = 0x00000055,
    #[strum(to_string = "BOOTCORE BootCfgHseValue")]
    BootCfgHseValue = 0x00000056,
    #[strum(to_string = "BOOTCORE BootCfgFsblDecryptPrio")]
    BootCfgFsblDecryptPrio = 0x00000057,
    #[strum(to_string = "BOOTCORE OtpHwConfigurationSLW")]
    OtpHwConfigurationSLW = 0x00000058,
    #[strum(to_string = "BOOTCORE NoUsbDpPullupOtpBitValue")]
    NoUsbDpPullupOtpBitValue = 0x00000060,
    #[strum(to_string = "BOOTCORE NoCpuPllOtpBitValue")]
    NoCpuPllOtpBitValue = 0x00000061,
    #[strum(to_string = "BOOTCORE Pll1StartNotDisabledByOtpBit")]
    Pll1StartNotDisabledByOtpBit = 0x00000062,
    #[strum(to_string = "BOOTCORE DebugNotLocked")]
    DebugNotLocked = 0x00000065,
    #[strum(to_string = "BOOTCORE DebugLocked")]
    DebugLocked = 0x00000066,
    #[strum(to_string = "BOOTCORE NoDataCacheBitValue")]
    NoDataCacheBitValue = 0x00000074,
    #[strum(to_string = "BOOTCORE BootModeDEVBOOT")]
    BootModeDEVBOOT = 0x00000092,
    #[strum(to_string = "BOOTCORE DevBootAborted")]
    DevBootAborted = 0x00000093,
    #[strum(to_string = "BOOTCORE BootModeNOBOOT")]
    BootModeNOBOOT = 0x00000094,
    #[strum(to_string = "BOOTCORE NOBOOTLoopSVCSecure")]
    NOBOOTLoopSVCSecure = 0x00000095,
    #[strum(to_string = "BOOTCORE BootModeSECUREBOOT")]
    BootModeSECUREBOOT = 0x00000097,
    #[strum(to_string = "BOOTCORE BootRomVer")]
    BootRomVer = 0x00000155,
    #[strum(to_string = "BOOTCORE BootRomChipVer")]
    BootRomChipVer = 0x00000156,
    #[strum(to_string = "BOOTCORE BootRomCutVer")]
    BootRomCutVer = 0x00000157,
    #[strum(to_string = "BOOTCORE BootRomForRtlVer")]
    BootRomForRtlVer = 0x00000158,
    #[strum(to_string = "BOOTCORE BootRomTargetPlatform")]
    BootRomTargetPlatform = 0x00000159,
    #[strum(to_string = "BOOTCORE BootRomMaskVer")]
    BootRomMaskVer = 0x0000015A,
    #[strum(to_string = "BOOTCORE BootPinsSrcSel")]
    BootPinsSrcSel = 0x00001001,
    #[strum(to_string = "BOOTCORE OtpOverrideBootPins")]
    OtpOverrideBootPins = 0x00001002,
    #[strum(to_string = "BOOTCORE SRCSEL_UNKNOWN")]
    SrcselUnknown = 0x0000101F,
    #[strum(to_string = "BOOTCORE SRCSEL_SERIAL")]
    SrcselSerial = 0x00001020,
    #[strum(to_string = "BOOTCORE SRCSEL_SDCARD_SDMMC1")]
    SrcselSdcardSdmmc1 = 0x00001021,
    #[strum(to_string = "BOOTCORE SRCSEL_EMMC_SDMMC1")]
    SrcselEmmcSdmmc1 = 0x00001022,
    #[strum(to_string = "BOOTCORE SRCSEL_DEV_BOOT_NONE")]
    SrcselDevBootNone = 0x00001023,
    #[strum(to_string = "BOOTCORE SRCSEL_SNOR_OSPI1")]
    SrcselSnorOspi1 = 0x00001024,
    #[strum(to_string = "BOOTCORE SRCSEL_SNAND_OSPI1")]
    SrcselSnandOspi1 = 0x00001025,
    #[strum(to_string = "BOOTCORE SRCSEL_PNAND_FMC")]
    SrcselPnandFmc = 0x00001026,
    #[strum(to_string = "BOOTCORE SRCSEL_SDCARD_SDMMC2")]
    SrcselSdcardSdmmc2 = 0x00001027,
    #[strum(to_string = "BOOTCORE SRCSEL_EMMC_SDMMC2")]
    SrcselEmmcSdmmc2 = 0x00001028,
    #[strum(to_string = "BOOTCORE SRCSEL_HYPERFLASH_OSPI1")]
    SrcselHyperflashOspi1 = 0x00001029,
    #[strum(to_string = "BOOTCORE SerialFallback")]
    SerialFallback = 0x00001032,
    #[strum(to_string = "BOOTCORE ImageVersionCounterNewProgVal")]
    ImageVersionCounterNewProgVal = 0x00001050,
    #[strum(to_string = "BOOTCORE ImageVersionTooBig")]
    ImageVersionTooBig = 0x00001051,
    #[strum(to_string = "BOOTCORE VerifyErrorWhileProgrammingImageCounter")]
    VerifyErrorWhileProgrammingImageCounter = 0x00001052,
    #[strum(to_string = "BOOTCORE AuthNewImageVersionCounterProgSuccess")]
    AuthNewImageVersionCounterProgSuccess = 0x00001053,
    #[strum(to_string = "BOOTCORE HseFrequencyDetected")]
    HseFrequencyDetected = 0x00002400,
    #[strum(to_string = "BOOTCORE HseDigBypassDetected")]
    HseDigBypassDetected = 0x00002401,
    #[strum(to_string = "BOOTCORE HseAnalogBypassDetected")]
    HseAnalogBypassDetected = 0x00002402,
    #[strum(to_string = "BOOTCORE HseNoBypass")]
    HseNoBypass = 0x00002403,
    #[strum(to_string = "BOOTCORE HseFreqDetectDisabled")]
    HseFreqDetectDisabled = 0x00002404,
    #[strum(to_string = "BOOTCORE HseBypassDetectDisabled")]
    HseBypassDetectDisabled = 0x00002405,
    #[strum(to_string = "BOOTCORE HseFrequencyDetectFailed")]
    HseFrequencyDetectFailed = 0x00002406,
    #[strum(to_string = "BOOTCORE HseFrequencyFallBackSolution")]
    HseFrequencyFallBackSolution = 0x00002407,
    #[strum(to_string = "BOOTCORE HseFreqDetectMeasuredKHz")]
    HseFreqDetectMeasuredKHz = 0x00002408,
    #[strum(to_string = "BOOTCORE HwResetPOR")]
    HwResetPOR = 0x00002500,
    #[strum(to_string = "BOOTCORE HwResetBOR")]
    HwResetBOR = 0x00002501,
    #[strum(to_string = "BOOTCORE HwResetPin")]
    HwResetPin = 0x00002502,
    #[strum(to_string = "BOOTCORE HwResetSft")]
    HwResetSft = 0x00002506,
    #[strum(to_string = "BOOTCORE HwResetIwdgSys")]
    HwResetIwdgSys = 0x00002508,
    #[strum(to_string = "BOOTCORE HwResetWwdgSys")]
    HwResetWwdgSys = 0x00002509,
    #[strum(to_string = "DWNLDMGR AssertBlocking")]
    DownloadManagerAssertBlocking = 0x1D000001,
    #[strum(to_string = "DWNLDMGR WrongMagicNumber")]
    WrongMagicNumber = 0x1D000002,
    #[strum(to_string = "DWNLDMGR ImageLengthTooSmall")]
    ImageLengthTooSmall = 0x1D000003,
    #[strum(to_string = "DWNLDMGR ImageLengthTooBig")]
    ImageLengthTooBig = 0x1D000004,
    #[strum(to_string = "DWNLDMGR EntryPointOutOfRange")]
    EntryPointOutOfRange = 0x1D000005,
    #[strum(to_string = "DWNLDMGR WrongImageChecksum")]
    WrongImageChecksum = 0x1D000006,
    #[strum(to_string = "DWNLDMGR WrongHeaderVersion")]
    WrongHeaderVersion = 0x1D000007,
    #[strum(to_string = "DWNLDMGR UnknownExtensionHeader")]
    UnknownExtensionHeader = 0x1D000008,
    #[strum(to_string = "DWNLDMGR FoundFsblDecryptionHeader")]
    FoundFsblDecryptionHeader = 0x1D000009,
    #[strum(to_string = "DWNLDMGR FoundPkhKeyRevocationHeader")]
    FoundPkhKeyRevocationHeader = 0x1D00000A,
    #[strum(to_string = "DWNLDMGR WrongExtensionHeaderLength")]
    WrongExtensionHeaderLength = 0x1D00000B,
    #[strum(to_string = "DWNLDMGR WrongCipherKeySize")]
    WrongCipherKeySize = 0x1D00000C,
    #[strum(to_string = "DWNLDMGR ExtensionFlagsMismatch")]
    ExtensionFlagsMismatch = 0x1D00000D,
    #[strum(to_string = "DWNLDMGR WrongNumberOfPublicKeyHash")]
    WrongNumberOfPublicKeyHash = 0x1D00000E,
    #[strum(to_string = "DWNLDMGR WrongPublicKeyIndex")]
    WrongPublicKeyIndex = 0x1D00000F,
    #[strum(to_string = "DWNLDMGR FoundPkhAuthenticationHeader")]
    FoundPkhAuthenticationHeader = 0x1D000010,
    #[strum(to_string = "DWNLDMGR FoundPaddingHeader")]
    FoundPaddingHeader = 0x1D000011,
    #[strum(to_string = "OSPI TryingSECBL1")]
    TryingSECBL1 = 0x80000001,
    #[strum(to_string = "OSPI TryingSECBL2")]
    TryingSECBL2 = 0x80000002,
    #[strum(to_string = "OSPI TryingSingleMode")]
    TryingSingleMode = 0x80000003,
    #[strum(to_string = "OSPI TryingDualMode")]
    TryingDualMode = 0x80000004,
    #[strum(to_string = "OSPI FoundGpt")]
    FoundGpt = 0x80000005,
    #[strum(to_string = "OSPI FoundMagicAtDefaultLocation")]
    FoundMagicAtDefaultLocation = 0x80000006,
    #[strum(to_string = "OSPI UseOffsets")]
    UseOffsets = 0x80000007,
    #[strum(to_string = "OSPI WrongImageLen")]
    WrongImageLen = 0x80000008,
    #[strum(to_string = "OSPI Timeout")]
    Timeout = 0x80000009,
    #[strum(to_string = "OSPI Assertion")]
    OspiAssertion = 0x8000000A,
    #[strum(to_string = "MMC AcknowledgeErr")]
    AcknowledgeErr = 0x13000001,
    #[strum(to_string = "MMC AcknowledgeTimeout")]
    AcknowledgeTimeout = 0x13000002,
    #[strum(to_string = "MMC CardNotDetected")]
    CardNotDetected = 0x13000003,
    #[strum(to_string = "MMC DataCrcErr")]
    DataCrcErr = 0x13000004,
    #[strum(to_string = "MMC DataTimeout")]
    DataTimeout = 0x13000005,
    #[strum(to_string = "MMC InvalidParameter")]
    MmcInvalidParameter = 0x13000006,
    #[strum(to_string = "MMC DmaTransferErr")]
    DmaTransferErr = 0x13000007,
    #[strum(to_string = "MMC CmdTimeoutErr")]
    CmdTimeoutErr = 0x13000008,
    #[strum(to_string = "MMC CmdCrcErr")]
    CmdCrcErr = 0x13000009,
    #[strum(to_string = "MMC AddAlignErr")]
    AddAlignErr = 0x1300000A,
    #[strum(to_string = "MMC NotEnoughBootDataRxErr")]
    NotEnoughBootDataRxErr = 0x1300000B,
    #[strum(to_string = "MMC ImageCopiedIsNotComplete")]
    ImageCopiedIsNotComplete = 0x1300000C,
    #[strum(to_string = "MMC ImageCopiedHeaderSizeZero")]
    ImageCopiedHeaderSizeZero = 0x1300000D,
    #[strum(to_string = "MMC AttemptBootDespiteErrors")]
    AttemptBootDespiteErrors = 0x1300000E,
    #[strum(to_string = "MMC GotDataEndFlagWithNoErrors")]
    GotDataEndFlagWithNoErrors = 0x1300000F,
    #[strum(to_string = "MMC NbBytesCopiedInSysram")]
    NbBytesCopiedInSysram = 0x13000010,
    #[strum(to_string = "MMC ImageCopiedHeaderNotFound")]
    ImageCopiedHeaderNotFound = 0x13000011,
    #[strum(to_string = "MMC TrySecBL1")]
    TrySecBL1 = 0x13000012,
    #[strum(to_string = "MMC NotFSBLFound")]
    NotFSBLFound = 0x13000013,
    #[strum(to_string = "MMC FsblsFound")]
    MmcFsblsFound = 0x13000014,
    #[strum(to_string = "MMC FailedSecBL1TrySecBL2")]
    FailedSecBL1TrySecBL2 = 0x13000015,
    #[strum(to_string = "MMC InitError")]
    InitError = 0x13000016,
    #[strum(to_string = "MMC TransferFailed")]
    MmcTransferFailed = 0x13000017,
    #[strum(to_string = "MMC GPTFound")]
    MmcGPTFound = 0x13000018,
    #[strum(to_string = "MMC NotGPTFound")]
    MmcNotGPTFound = 0x13000019,
    #[strum(to_string = "MMC Assertion")]
    Assertion = 0x1300001F,
    #[strum(to_string = "USB Init")]
    Init = 0x14000000,
    #[strum(to_string = "USB Loop")]
    Loop = 0x14000001,
    #[strum(to_string = "USB Selection")]
    UsbSelection = 0x14000002,
    #[strum(to_string = "USB DFU_DownloadComplete")]
    DfuDownloadComplete = 0x14000004,
    #[strum(to_string = "USB DFU_GetStatus")]
    DfuGetStatus = 0x14000005,
    #[strum(to_string = "USB DFU_GetStatus_GoTo_Idle")]
    DfuGetStatusGoToIdle = 0x14000006,
    #[strum(to_string = "USB DFU_END_OF_DNLOAD")]
    DfuEndOfDownload = 0x14000007,
    #[strum(to_string = "USB DFU_DNLOAD")]
    DfuDNLOAD = 0x14000008,
    #[strum(to_string = "USB DFU_UPLOAD")]
    DfuUPLOAD = 0x14000009,
    #[strum(to_string = "USB DFU_GETSTATUS")]
    DfuGETSTATUS = 0x1400000A,
    #[strum(to_string = "USB DFU_CLRSTATUS")]
    DfuCLRSTATUS = 0x1400000B,
    #[strum(to_string = "USB DFU_GETSTATE")]
    DfuGETSTATE = 0x1400000C,
    #[strum(to_string = "USB DFU_ABORT")]
    DfuABORT = 0x1400000D,
    #[strum(to_string = "USB DFU_DETACH")]
    DfuDETACH = 0x1400000E,
    #[strum(to_string = "USB DFU_LEAVE")]
    DfuLEAVE = 0x1400000F,
    #[strum(to_string = "USB DFU_DataOut")]
    DfuDataOut = 0x14000010,
    #[strum(to_string = "USB DFU_GetStatusMedia")]
    DfuGetStatusMedia = 0x14000011,
    #[strum(to_string = "USB DFU_SRAMWrite")]
    DfuSRAMWrite = 0x14000012,
    #[strum(to_string = "USB DFU_SRAMWrite_CRC")]
    DfuSramWriteCrc = 0x14000013,
    #[strum(to_string = "USB DFU_SRAMWrite_imgL")]
    DfuSramWriteImgl = 0x14000014,
    #[strum(to_string = "USB DFU_Init")]
    DfuInit = 0x14000015,
    #[strum(to_string = "USB DFU_SET_INTERFACE")]
    DfuSetInterface = 0x14000016,
    #[strum(to_string = "USB DFU_SET_INTERFACE_ERR")]
    DfuSetInterfaceError = 0x14000017,
    #[strum(to_string = "USB DFU_Get_INTERFACE")]
    DfuGetInterface = 0x14000018,
    #[strum(to_string = "USB DFU_LEAVE_EP0_TxReady")]
    DfuLeaveEp0TxReady = 0x14000019,
    #[strum(to_string = "USB ClockTree_Failed")]
    UsbClockTreeFailed = 0x14000020,
    #[strum(to_string = "USB WrongDataTransfer")]
    WrongDataTransfer = 0x14000021,
    #[strum(to_string = "USB DataTransfered")]
    DataTransfered = 0x14000022,
    #[strum(to_string = "USB Power_Failed")]
    PowerFailed = 0x14000023,
    #[strum(to_string = "USB DFU_DetachComplete")]
    DfuDetachComplete = 0x14000030,
    #[strum(to_string = "USB DEBUG")]
    DEBUG = 0x14000031,
    #[strum(to_string = "USB DFU_SPEC_CMD_NOT_SUPPORTED")]
    DfuSpecCmdNotSupported = 0x14000040,
    #[strum(to_string = "USB DFU_GetUsrStringDesc")]
    DfuGetUsrStringDesc = 0x14000041,
    #[strum(to_string = "USB CallingSetLockedUnprovd")]
    UsbCallingSetLockedUnprovd = 0x14000050,
    #[strum(to_string = "USB WrongDestCheck")]
    WrongDestCheck = 0x14000051,
    #[strum(to_string = "USB Assertion")]
    UsbAssertion = 0x140FFFFF,
    #[strum(to_string = "UART Selection")]
    UartSelection = 0x15000001,
    #[strum(to_string = "UART PeripheralSerialBootLoopStart")]
    PeripheralSerialBootLoopStart = 0x15000002,
    #[strum(to_string = "UART PacketNumber")]
    PacketNumber = 0x15000003,
    #[strum(to_string = "UART PacketSize")]
    PacketSize = 0x15000004,
    #[strum(to_string = "UART PacketXor")]
    PacketXor = 0x15000005,
    #[strum(to_string = "UART ImageLength")]
    ImageLength = 0x15000006,
    #[strum(to_string = "UART Cursor")]
    Cursor = 0x15000007,
    #[strum(to_string = "UART NACK")]
    NACK = 0x15000008,
    #[strum(to_string = "UART Abort")]
    Abort = 0x15000009,
    #[strum(to_string = "UART ActivityDetected")]
    ActivityDetected = 0x1500000A,
    #[strum(to_string = "UART ActivityDetecting")]
    ActivityDetecting = 0x1500000B,
    #[strum(to_string = "UART ReceivedByte")]
    ReceivedByte = 0x1500000C,
    #[strum(to_string = "UART DownloadFinished")]
    DownloadFinished = 0x1500000D,
    #[strum(to_string = "UART Start")]
    Start = 0x1500000E,
    #[strum(to_string = "UART CallingSetLockedUnprovd")]
    UartCallingSetLockedUnprovd = 0x15000020,
    #[strum(to_string = "UART AssertBlocking")]
    UartAssertBlocking = 0x15000100,
    #[strum(to_string = "USB InvalidInterrupt")]
    InvalidInterrupt = 0x14000BB0,
    #[strum(to_string = "TIMEOUT Assertion")]
    TimeoutAssertion = 0x29000000,
    #[strum(to_string = "SD InvalidParameter")]
    SdInvalidParameter = 0x12000000,
    #[strum(to_string = "SD InitFailed")]
    InitFailed = 0x12000001,
    #[strum(to_string = "SD TransferFailed")]
    SdTransferFailed = 0x12000002,
    #[strum(to_string = "SD CardDetected")]
    CardDetected = 0x12000003,
    #[strum(to_string = "SD NoCardResponse")]
    NoCardResponse = 0x12000004,
    #[strum(to_string = "SD TryFSBL1")]
    TryFSBL1 = 0x12000005,
    #[strum(to_string = "SD FailedFSBL1TryFSBL2")]
    FailedFSBL1TryFSBL2 = 0x12000006,
    #[strum(to_string = "SD InitDetailedErrorDesc")]
    InitDetailedErrorDesc = 0x12000007,
    #[strum(to_string = "SD ImageTooBig")]
    ImageTooBig = 0x12000008,
    #[strum(to_string = "SD ImageLengthZero")]
    ImageLengthZero = 0x12000009,
    #[strum(to_string = "SD StdCapacityCardV11")]
    StdCapacityCardV11 = 0x1200000A,
    #[strum(to_string = "SD StdCapacityCardV20")]
    StdCapacityCardV20 = 0x1200000B,
    #[strum(to_string = "SD HighCapacityCardSDHCOrSDXC")]
    HighCapacityCardSDHCOrSDXC = 0x1200000C,
    #[strum(to_string = "SD UnknownCapacityCard")]
    UnknownCapacityCard = 0x1200000D,
    #[strum(to_string = "SD OverallRetryCnt")]
    OverallRetryCnt = 0x1200000E,
    #[strum(to_string = "SD ImageHeaderNotFound")]
    ImageHeaderNotFound = 0x1200000F,
    #[strum(to_string = "SD NotGPTFound")]
    SdNotGPTFound = 0x12000010,
    #[strum(to_string = "SD FsblsFound")]
    SdFsblsFound = 0x12000011,
    #[strum(to_string = "SD GPTFound")]
    SdGPTFound = 0x12000012,
    #[strum(to_string = "SD NoFSBLFound")]
    NoFSBLFound = 0x12000013,
    #[strum(to_string = "SD Assertion")]
    SdAssertion = 0x1200001F,
    #[strum(to_string = "INFHARDLIB AssertBlocking")]
    InfHardLibAssertBlocking = 0x2E000001,
    #[strum(to_string = "Unknown code!")]
    Unknown,
}

impl From<u32> for Type {
    fn from(value: u32) -> Self {
        Type::from_repr(value).unwrap_or(Type::Unknown)
    }
}

